FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .

RUN pip install uv && uv pip install --system --no-cache -r requirements.txt

COPY . .

EXPOSE 8002

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8002"]